name: Orbis672

on:
  push:
    branches: [ master, develop ]
  pull_request:
    branches: [ master, develop ]

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
        # Checkout the repository
      - uses: actions/checkout@v2
        # Install required stuff needed to build Mira
      - name: preinstall
        run: wget -q -O - https://files.viva64.com/etc/pubkey.txt | sudo apt-key add -; sudo wget -O /etc/apt/sources.list.d/viva64.list https://files.viva64.com/etc/viva64.list; sudo apt-get update; sudo apt install build-essential git clang lldb clang-tidy clang-tools cppcheck pvs-studio
        # Handle loader crap
      - name: create loader directories
        run: cd loader; MIRA_PLATFORM=MIRA_PLATFORM_ORBIS_BSD_672 make create
      - name: clean loader
        run: cd loader; MIRA_PLATFORM=MIRA_PLATFORM_ORBIS_BSD_672 make clean
      - name: create mira directories
        run: cd kernel; MIRA_PLATFORM=MIRA_PLATFORM_ORBIS_BSD_672 make create
      - name: clean mira
        run: cd kernel; MIRA_PLATFORM=MIRA_PLATFORM_ORBIS_BSD_672 make clean
        # 6.72 Support
      - name: make 6.72 loader
        run: cd loader; MIRA_PLATFORM=MIRA_PLATFORM_ORBIS_BSD_672 MIRA_CHECKS=TRUE pvs-studio-analyzer trace -- make
      - name: make 6.72 elf
        run: cd kernel; MIRA_PLATFORM=MIRA_PLATFORM_ORBIS_BSD_672 ADD_GIT_HASH=TRUE MIRA_CHECKS=TRUE pvs-studio-analyzer trace -- make
      - name: rename 6.72 elf to bin
        run: rename kernel/build/Mira_Orbis_MIRA_PLATFORM_ORBIS_BSD_672.elf kernel/build/Mira_Orbis_MIRA_PLATFORM_ORBIS_BSD_672.bin
      - name: Upload 6.72 elfs
        uses: actions/upload-artifact@v2
        with:
          name: Mira_Orbis_MIRA_PLATFORM_ORBIS_BSD_672
          path: |
            loader/build/MiraLoader_Orbis_MIRA_PLATFORM_ORBIS_BSD_672.bin
            kernel/build/Mira_Orbis_MIRA_PLATFORM_ORBIS_BSD_672.bin
